// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Spider.Invoicing.API.Database;
using System;

namespace Spider.Invoicing.API.Migrations
{
    [DbContext(typeof(InvoicingContext))]
    [Migration("20180802142415_TemporatyInvoice")]
    partial class TemporatyInvoice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Spider.Invoicing.API.Database.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<decimal>("GrossAmmount")
                        .HasColumnType("money");

                    b.Property<string>("InvoiceNumber");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("money");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Spider.Invoicing.API.Database.Models.InvoiceTemporary", b =>
                {
                    b.Property<Guid>("InvoiceTemporaryId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<decimal>("GrossAmmount")
                        .HasColumnType("money");

                    b.Property<Guid?>("InvoiceId");

                    b.Property<string>("InvoiceNumber");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("money");

                    b.HasKey("InvoiceTemporaryId");

                    b.ToTable("TemporaryInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
