pipeline {
    agent any 

    stages {
        stage('Build') { 
              when {
                branch "uat"
            }    
            steps { 
                sh 'bash Spider.Invoicing.API/build.sh' 
            }
        }
        stage('Start') {
              when {
                branch "uat"
            }  
            steps {
                sh 'bash Spider.Invoicing.API/start.sh'
            }
        }
    }
}