pipeline {
    agent any 
	environment{
		APP_FOLDER='Spider.Invoicing.API'
	}
    stages {
        stage('Build') { 
              when {
                branch "uat"
            }    
            steps { 
				dir(APP_FOLDER){
					sh 'bash build.sh' 
				}
            }
        }
        stage('Start') {
              when {
                branch "uat"
            }  
            steps {
				dir(APP_FOLDER){
					sh 'bash start.sh'
				}
            }
        }
    }
}